/**
 * Wasp API
 * REST API for the Wasp node
 *
 * OpenAPI spec version: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FoundryOutputResponse {
    /**
    * The base tokens (uint64 as string)
    */
    'baseTokens': string;
    'foundryId': string;
    /**
    * The native token id
    */
    'nativeTokenId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "baseTokens",
            "baseName": "baseTokens",
            "type": "string",
            "format": "string"
        },
        {
            "name": "foundryId",
            "baseName": "foundryId",
            "type": "string",
            "format": "string"
        },
        {
            "name": "nativeTokenId",
            "baseName": "nativeTokenId",
            "type": "string",
            "format": "string"
        }    ];

    static getAttributeTypeMap() {
        return FoundryOutputResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

