/*
Wasp API

REST API for the Wasp node

API version: 0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the FoundryOutputResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FoundryOutputResponse{}

// FoundryOutputResponse struct for FoundryOutputResponse
type FoundryOutputResponse struct {
	// The base tokens (uint64 as string)
	BaseTokens string `json:"baseTokens"`
	FoundryId string `json:"foundryId"`
	// The native token id
	NativeTokenId string `json:"nativeTokenId"`
}

// NewFoundryOutputResponse instantiates a new FoundryOutputResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFoundryOutputResponse(baseTokens string, foundryId string, nativeTokenId string) *FoundryOutputResponse {
	this := FoundryOutputResponse{}
	this.BaseTokens = baseTokens
	this.FoundryId = foundryId
	this.NativeTokenId = nativeTokenId
	return &this
}

// NewFoundryOutputResponseWithDefaults instantiates a new FoundryOutputResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFoundryOutputResponseWithDefaults() *FoundryOutputResponse {
	this := FoundryOutputResponse{}
	return &this
}

// GetBaseTokens returns the BaseTokens field value
func (o *FoundryOutputResponse) GetBaseTokens() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseTokens
}

// GetBaseTokensOk returns a tuple with the BaseTokens field value
// and a boolean to check if the value has been set.
func (o *FoundryOutputResponse) GetBaseTokensOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseTokens, true
}

// SetBaseTokens sets field value
func (o *FoundryOutputResponse) SetBaseTokens(v string) {
	o.BaseTokens = v
}

// GetFoundryId returns the FoundryId field value
func (o *FoundryOutputResponse) GetFoundryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FoundryId
}

// GetFoundryIdOk returns a tuple with the FoundryId field value
// and a boolean to check if the value has been set.
func (o *FoundryOutputResponse) GetFoundryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FoundryId, true
}

// SetFoundryId sets field value
func (o *FoundryOutputResponse) SetFoundryId(v string) {
	o.FoundryId = v
}

// GetNativeTokenId returns the NativeTokenId field value
func (o *FoundryOutputResponse) GetNativeTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NativeTokenId
}

// GetNativeTokenIdOk returns a tuple with the NativeTokenId field value
// and a boolean to check if the value has been set.
func (o *FoundryOutputResponse) GetNativeTokenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NativeTokenId, true
}

// SetNativeTokenId sets field value
func (o *FoundryOutputResponse) SetNativeTokenId(v string) {
	o.NativeTokenId = v
}

func (o FoundryOutputResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FoundryOutputResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["baseTokens"] = o.BaseTokens
	toSerialize["foundryId"] = o.FoundryId
	toSerialize["nativeTokenId"] = o.NativeTokenId
	return toSerialize, nil
}

type NullableFoundryOutputResponse struct {
	value *FoundryOutputResponse
	isSet bool
}

func (v NullableFoundryOutputResponse) Get() *FoundryOutputResponse {
	return v.value
}

func (v *NullableFoundryOutputResponse) Set(val *FoundryOutputResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFoundryOutputResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFoundryOutputResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFoundryOutputResponse(val *FoundryOutputResponse) *NullableFoundryOutputResponse {
	return &NullableFoundryOutputResponse{value: val, isSet: true}
}

func (v NullableFoundryOutputResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFoundryOutputResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


