/*
Wasp API

REST API for the Wasp node

API version: 0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
)

// checks if the AccountOutputMetricItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountOutputMetricItem{}

// AccountOutputMetricItem struct for AccountOutputMetricItem
type AccountOutputMetricItem struct {
	LastMessage Output `json:"lastMessage"`
	Messages uint32 `json:"messages"`
	Timestamp time.Time `json:"timestamp"`
}

// NewAccountOutputMetricItem instantiates a new AccountOutputMetricItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountOutputMetricItem(lastMessage Output, messages uint32, timestamp time.Time) *AccountOutputMetricItem {
	this := AccountOutputMetricItem{}
	this.LastMessage = lastMessage
	this.Messages = messages
	this.Timestamp = timestamp
	return &this
}

// NewAccountOutputMetricItemWithDefaults instantiates a new AccountOutputMetricItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountOutputMetricItemWithDefaults() *AccountOutputMetricItem {
	this := AccountOutputMetricItem{}
	return &this
}

// GetLastMessage returns the LastMessage field value
func (o *AccountOutputMetricItem) GetLastMessage() Output {
	if o == nil {
		var ret Output
		return ret
	}

	return o.LastMessage
}

// GetLastMessageOk returns a tuple with the LastMessage field value
// and a boolean to check if the value has been set.
func (o *AccountOutputMetricItem) GetLastMessageOk() (*Output, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastMessage, true
}

// SetLastMessage sets field value
func (o *AccountOutputMetricItem) SetLastMessage(v Output) {
	o.LastMessage = v
}

// GetMessages returns the Messages field value
func (o *AccountOutputMetricItem) GetMessages() uint32 {
	if o == nil {
		var ret uint32
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *AccountOutputMetricItem) GetMessagesOk() (*uint32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Messages, true
}

// SetMessages sets field value
func (o *AccountOutputMetricItem) SetMessages(v uint32) {
	o.Messages = v
}

// GetTimestamp returns the Timestamp field value
func (o *AccountOutputMetricItem) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *AccountOutputMetricItem) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *AccountOutputMetricItem) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

func (o AccountOutputMetricItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountOutputMetricItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lastMessage"] = o.LastMessage
	toSerialize["messages"] = o.Messages
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize, nil
}

type NullableAccountOutputMetricItem struct {
	value *AccountOutputMetricItem
	isSet bool
}

func (v NullableAccountOutputMetricItem) Get() *AccountOutputMetricItem {
	return v.value
}

func (v *NullableAccountOutputMetricItem) Set(val *AccountOutputMetricItem) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountOutputMetricItem) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountOutputMetricItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountOutputMetricItem(val *AccountOutputMetricItem) *NullableAccountOutputMetricItem {
	return &NullableAccountOutputMetricItem{value: val, isSet: true}
}

func (v NullableAccountOutputMetricItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountOutputMetricItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


