/*
Wasp API

REST API for the Wasp node

API version: 0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
)

// checks if the AnchorOutputMetricItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnchorOutputMetricItem{}

// AnchorOutputMetricItem struct for AnchorOutputMetricItem
type AnchorOutputMetricItem struct {
	LastMessage Output `json:"lastMessage"`
	Messages uint32 `json:"messages"`
	Timestamp time.Time `json:"timestamp"`
}

// NewAnchorOutputMetricItem instantiates a new AnchorOutputMetricItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnchorOutputMetricItem(lastMessage Output, messages uint32, timestamp time.Time) *AnchorOutputMetricItem {
	this := AnchorOutputMetricItem{}
	this.LastMessage = lastMessage
	this.Messages = messages
	this.Timestamp = timestamp
	return &this
}

// NewAnchorOutputMetricItemWithDefaults instantiates a new AnchorOutputMetricItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnchorOutputMetricItemWithDefaults() *AnchorOutputMetricItem {
	this := AnchorOutputMetricItem{}
	return &this
}

// GetLastMessage returns the LastMessage field value
func (o *AnchorOutputMetricItem) GetLastMessage() Output {
	if o == nil {
		var ret Output
		return ret
	}

	return o.LastMessage
}

// GetLastMessageOk returns a tuple with the LastMessage field value
// and a boolean to check if the value has been set.
func (o *AnchorOutputMetricItem) GetLastMessageOk() (*Output, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastMessage, true
}

// SetLastMessage sets field value
func (o *AnchorOutputMetricItem) SetLastMessage(v Output) {
	o.LastMessage = v
}

// GetMessages returns the Messages field value
func (o *AnchorOutputMetricItem) GetMessages() uint32 {
	if o == nil {
		var ret uint32
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *AnchorOutputMetricItem) GetMessagesOk() (*uint32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Messages, true
}

// SetMessages sets field value
func (o *AnchorOutputMetricItem) SetMessages(v uint32) {
	o.Messages = v
}

// GetTimestamp returns the Timestamp field value
func (o *AnchorOutputMetricItem) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *AnchorOutputMetricItem) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *AnchorOutputMetricItem) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

func (o AnchorOutputMetricItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnchorOutputMetricItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lastMessage"] = o.LastMessage
	toSerialize["messages"] = o.Messages
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize, nil
}

type NullableAnchorOutputMetricItem struct {
	value *AnchorOutputMetricItem
	isSet bool
}

func (v NullableAnchorOutputMetricItem) Get() *AnchorOutputMetricItem {
	return v.value
}

func (v *NullableAnchorOutputMetricItem) Set(val *AnchorOutputMetricItem) {
	v.value = val
	v.isSet = true
}

func (v NullableAnchorOutputMetricItem) IsSet() bool {
	return v.isSet
}

func (v *NullableAnchorOutputMetricItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnchorOutputMetricItem(val *AnchorOutputMetricItem) *NullableAnchorOutputMetricItem {
	return &NullableAnchorOutputMetricItem{value: val, isSet: true}
}

func (v NullableAnchorOutputMetricItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnchorOutputMetricItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


